Repository googleapis/google-auth-library-java, pull requests merged in 2019-06, with the labels that each got.

#258 Update to latest app engine SDK version
  pom.xml
Labels: cla: yes

#263 Release google-auth-library-java v0.16.0
  README.md
  appengine/pom.xml
  bom/README.md
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: cla: yes

#264 Bump next snapshot
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: cla: yes

#267 Add credentials for autorelease
  .kokoro/release/stage.cfg
Labels: cla: yes

#269 Release google-auth-library-java v0.16.1
  README.md
  appengine/pom.xml
  bom/README.md
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#270 Bump next snapshot
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: cla: yes

#271 Autorelease will also auto publish
  .kokoro/build.sh
  .kokoro/release/stage.sh
  pom.xml
Labels: :rotating_light:, cla: yes

#275 README section for interop with google-http-client
  README.md
Labels: :rotating_light:, cla: yes

#268 Import http client bom for dependency management
  pom.xml
Labels: :rotating_light:, cla: yes

#283 Adds metadata-flavor header to metadata server ping for compute engine
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
Labels: cla: yes

#284 Release google-auth-library-java v0.16.2
  README.md
  appengine/pom.xml
  bom/README.md
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#285 Bump next snapshot
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: cla: yes
