Repository googleapis/google-auth-library-java, pull requests merged in 2019-08, with the labels that each got.

#318 remove final on local variables
  appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
Labels: cla: yes

#319 build: run in debug mode
  .kokoro/continuous/propose_release.sh
Labels: cla: yes

#320 revert: "build: run in debug mode"
  .kokoro/continuous/propose_release.sh
Labels: cla: yes

#290 feat: adds JwtCredentials with custom claims
  oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
  oauth2_http/java/com/google/auth/oauth2/JwtCredentials.java
  oauth2_http/java/com/google/auth/oauth2/JwtProvider.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
  oauth2_http/pom.xml
  pom.xml
  renovate.json
Labels: cla: yes, semver: minor

#322 docs: fix README link to javadoc
  README.md
Labels: cla: yes

#323 Remove obsolete parent POM
  pom.xml
Labels: cla: yes

#326 feat: add Automatic-Module-Name to manifest (#324)
  appengine/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
Labels: cla: yes

#303 feat: add IDTokenCredential support
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IamUtils.java
  oauth2_http/java/com/google/auth/oauth2/IdToken.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdTokenCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdTokenTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockIAMCredentialsServiceTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: cla: yes, semver: minor

#327 docs: backfill CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes

#332 docs: fix minor typo in google-auth-library-bom README
  bom/README.md
Labels: cla: yes

#330 chore: cleanup javadoc warnings
  oauth2_http/java/com/google/auth/oauth2/IdToken.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
Labels: cla: yes

#331 feat: allow arbitrary additional claims for JwtClaims
  oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
  oauth2_http/java/com/google/auth/oauth2/JwtCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtClaimsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
Labels: cla: yes

#329 chore: hide `IdToken#getJsonWebSignature()`
  oauth2_http/java/com/google/auth/oauth2/IdToken.java
Labels: cla: yes

#328 chore: release 0.17.0
  CHANGELOG.md
  README.md
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes, type: process

#333 chore: release 0.17.1-SNAPSHOT
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: cla: yes, type: process

#336 fix: allow unset/null privateKeyId for JwtCredentials
  oauth2_http/java/com/google/auth/oauth2/JwtCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
Labels: cla: yes

#337 chore: release 0.17.1
  CHANGELOG.md
  README.md
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes, type: process

#338 chore: release 0.17.2-SNAPSHOT
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes, type: process
