Repository googleapis/google-auth-library-java, pull requests merged in 2019-10, with the labels that each got.

#352 Update doc
  bom/README.md
Labels: cla: yes

#353 Update Guava to 28.1
  pom.xml
Labels: cla: yes

#358 move autovalue into annotation processor path instead of classpath
  oauth2_http/pom.xml
  pom.xml
Labels: cla: yes, semver: patch, type: cleanup

#351 chore: release 0.17.4
  CHANGELOG.md
  README.md
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes, type: process

#360 build: fix version and tags for release-please
  versions.txt
Labels: cla: yes

#362 chore: release 0.18.0
  CHANGELOG.md
  README.md
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes, type: process

#366 Update appengine API
  pom.xml
Labels: cla: yes, priority: p2, semver: patch

#370 Remove outdated comment on explicit IP address
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
Labels: cla: yes

#372 fix: xml syntax error in bom/README.md
  bom/README.md
Labels: cla: yes
