Repository googleapis/google-auth-library-java, pull requests merged in 2020-12, with the labels that each got.

#509 fix: quotaProjectId should be applied for cached `getRequestMetadata(URI, Executor, RequestMetadataCallback)`
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: cla: yes

#520 fix: updates AWS credential source
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/StsRequestHandler.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: cla: yes

#524 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#514 feat: allow custom scopes for compute engine creds
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
Labels: automerge, cla: yes

#515 feat: allow custom lifetime for ImpersonatedCredentials
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
Labels: automerge, cla: yes

#528 fix: style nits
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
Labels: cla: yes

#473 fix!: privatize deprecated constructor
  oauth2_http/clirr-ignored-differences.xml
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
Labels: cla: yes

#530 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, merge

#531 fix: switch to GSON
  oauth2_http/java/com/google/auth/oauth2/ClientId.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/javatests/com/google/auth/TestUtils.java
  oauth2_http/javatests/com/google/auth/oauth2/ClientIdTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
  oauth2_http/pom.xml
Labels: cla: yes

#527 fix: use default timeout if given 0 for ImpersonatedCredentials
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
Labels: cla: yes

#529 fix: per google style, logger is lower case
  appengine/java/com/google/auth/appengine/AppEngineCredentials.java
Labels: cla: yes
