Repository googleapis/google-auth-library-java, pull requests merged in 2021-11, with the labels that each got.

#780 feat: next release from main branch is 1.3.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#781 ci: configure the protected branch
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
Labels: kokoro:force-run, cla: yes, automerge

#791 chore: cleanup cloud RAD generation
  pom.xml
Labels: cla: yes, automerge
