Repository googleapis/google-auth-library-java, pull requests merged in 2021-04, with the labels that each got.

#622 chore: add GCS_BUCKET env var
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
Labels: automerge, cla: yes

#623 chore: add integration.cfg to excludes list in synth.py
  synth.py
Labels: automerge, cla: yes

#628 deps: update guava patch
  pom.xml
Labels: cla: yes

#629 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:force-run

#632 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#634 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#641 chore: add cloud-rad doc generation
  pom.xml
Labels: cla: yes

#642 fix: use orginal url as audience for self signed jwt if scheme or host is null
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
Labels: cla: yes
