Repository googleapis/google-auth-library-java, pull requests merged in 2021-01, with the labels that each got.

#532 refactor: use StandardCharsets.UTF_8 constant
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
Labels: automerge, cla: yes

#536 fix typos in Javadoc
  oauth2_http/java/com/google/auth/oauth2/JwtProvider.java
Labels: cla: yes

#516 feat: allow set lifetime for service account creds
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: cla: yes

#539 fix: replace non-precondition use of Preconditions
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
Labels: cla: yes, type: cleanup

#537 fix: remove deprecated methods
  appengine/java/com/google/auth/appengine/AppEngineCredentials.java
  appengine/javatests/com/google/auth/appengine/AppEngineCredentialsTest.java
  appengine/pom.xml
Labels: cla: yes

#543 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#538 feat: promote IdToken and JWT features
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdToken.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/JwtProvider.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java
Labels: automerge, cla: yes

#545 revert to BSD license
  LICENSE
  synth.py
Labels: cla: yes

#548 build: migrate to flakybot
  .kokoro/build.sh
Labels: automerge, cla: yes
