Repository googleapis/google-auth-library-java, pull requests merged in 2021-07, with the labels that each got.

#685 feat: Adding functional tests for Service Account
  oauth2_http/javatests/com/google/auth/oauth2/functional/FTServiceAccountCredentialsTest.java
  oauth2_http/pom.xml
Labels: cla: yes

#691 feat: downscoping with credential access boundaries
  oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2CredentialsWithRefresh.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/StsRequestHandler.java
  oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsWithRefreshTest.java
Labels: cla: yes

#689 feat: allow scopes for self signed jwt
  oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtClaimsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
Labels: cla: yes

#698 test: adds integration tests for downscoping with credential access boundaries
  CHANGELOG.md
  README.md
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/java/com/google/auth/oauth2/JwtClaims.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ITDownscopingTest.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtClaimsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/functional/FTServiceAccountCredentialsTest.java
  oauth2_http/pom.xml
  pom.xml
  scripts/downscoping-with-cab-setup.sh
  versions.txt
Labels: cla: yes

#699 fix: use source credential expiration when STS does not return expires_in
  oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/StsRequestHandler.java
  oauth2_http/java/com/google/auth/oauth2/StsTokenExchangeResponse.java
  oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/StsRequestHandlerTest.java
Labels: cla: yes

#693 fix: Add shopt -s nullglob to dependencies script
  .kokoro/coerce_logs.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full, kokoro:force-run

#704 feat: GA release of google-auth-library-java (ver 1.0.0)
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .repo-metadata.json
  pom.xml
Labels: automerge, cla: yes

#707 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#708 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: automerge, cla: yes
