Repository googleapis/google-auth-library-java, pull requests merged in 2021-03, with the labels that each got.

#587 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#588 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#589 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#572 feat: add self signed jwt support
  oauth2_http/java/com/google/auth/oauth2/AppEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AppEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
Labels: cla: yes

#581 test: adds integration tests for workload identity federation
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/java/com/google/auth/oauth2/EnvironmentProvider.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
  oauth2_http/java/com/google/auth/oauth2/SystemEnvironmentProvider.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/TestEnvironmentProvider.java
  oauth2_http/pom.xml
  scripts/workloadidentityfederation-setup.sh
Labels: automerge, cla: yes

#601 fix: fix service account credentials createScopedRequired
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: cla: yes

#599 fix: support AWS_DEFAULT_REGION env var
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
Labels: automerge, cla: yes

#605 fix: follow up fix service account credentials createScopedRequired
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: cla: yes

#616 chore: Re-generated to pick up changes from synthtool
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: partial
