Repository googleapis/google-auth-library-java, pull requests merged in 2021-05, with the labels that each got.

#647 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#651 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#649 chore: remove codecov
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/presubmit/common.cfg
  README.md
  codecov.yaml
  synth.metadata
Labels: automerge, cla: yes

#658 feat: added getter for credentials object in HttpCredentialsAdapter
  oauth2_http/java/com/google/auth/http/HttpCredentialsAdapter.java
  oauth2_http/javatests/com/google/auth/http/HttpCredentialsAdapterTest.java
  oauth2_http/pom.xml
Labels: cla: yes

#664 build: configure branch 0.25.2-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#665 build: switch all clients to use the google endpoint on sonatype
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
Labels: automerge, cla: yes

#666 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: cla: yes

#656 feat: Returning an issuer claim on request errors
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: cla: yes

#673 chore: Re-generated to pick up changes from synthtool
  .github/workflows/ci.yaml
  .kokoro/build.sh
  .kokoro/presubmit/common.cfg
  .kokoro/release/publish_javadoc11.sh
  codecov.yaml
  synth.metadata
Labels: cla: yes, context: partial

#671 chore: update cloud-rad doclet
  pom.xml
Labels: automerge, cla: yes

#674 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#677 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#613 feat: add impersonation credentials to ADC
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
Labels: cla: yes

#650 feat: add Id token support for UserCredentials
  .gitignore
  oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: cla: yes
