Repository googleapis/google-auth-library-java, pull requests merged in 2021-09, with the labels that each got.

#734 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, automerge

#719 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, automerge, context: partial

#736 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  synth.metadata
Labels: cla: yes, context: none

#735 chore: update java docfx doclet
  pom.xml
Labels: cla: yes

#738 chore: stop requiring linkage-monitor check
  .github/sync-repo-settings.yaml
Labels: cla: yes

#737 ci: removing linkage-monitor from the required checks
  .github/release-trigger.yml
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, automerge, context: partial

#729 feat: add support for Workforce Pools
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
  oauth2_http/java/com/google/auth/oauth2/StsTokenExchangeRequest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
Labels: cla: yes

#741 fix: workforce audience
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
Labels: cla: yes

#739 chore: update java-docfx-doclet version
  pom.xml
Labels: cla: yes, automerge

#742 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, automerge

#743 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
Labels: cla: yes, automerge

#748 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes, automerge

#751 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, automerge

#752 fix: allow empty workforce_pool_user_project
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
Labels: cla: yes

#749 fix: timing of stale token refreshes on ComputeEngine
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
  oauth2_http/javatests/com/google/auth/oauth2/MockRequestMetadataCallback.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
Labels: cla: yes
