Repository googleapis/google-auth-library-java, pull requests merged in 2022-08, with the labels that each got.

#932 fix: expiration time of the ImpersonatedCredentials token depending on the current host's timezone
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
Labels: automerge, size: m

#927 docs(samples): added auth samples and tests
  samples/snippets/pom.xml
  samples/snippets/src/main/java/AuthenticateExplicit.java
  samples/snippets/src/main/java/AuthenticateImplicitWithAdc.java
  samples/snippets/src/main/java/IdTokenFromImpersonatedCredentials.java
  samples/snippets/src/main/java/IdTokenFromMetadataServer.java
  samples/snippets/src/main/java/IdTokenFromServiceAccount.java
  samples/snippets/src/main/java/VerifyGoogleIdToken.java
  samples/snippets/src/test/java/SnippetsIT.java
Labels: samples, size: l

#955 fix: updates executable response spec for executable-sourced credentials
  README.md
  oauth2_http/java/com/google/auth/oauth2/ExecutableResponse.java
  oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java
  oauth2_http/java/com/google/auth/oauth2/PluggableAuthHandler.java
  oauth2_http/javatests/com/google/auth/oauth2/ExecutableResponseTest.java
  oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthHandlerTest.java
Labels: size: l

#959 feat: workforce identity federation
  README.md
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: size: l

#971 fix: Add Test to validate 0x20 in token
  oauth2_http/javatests/com/google/auth/oauth2/IdTokenTest.java
Labels: kokoro:force-run, automerge, size: xs

#979 fix: change revoke request from get to post
  oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
  oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
Labels: size: s

#983 fix: add retries to public key fetch
  oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java
  oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java
Labels: size: m
