Repository googleapis/google-auth-library-java, pull requests merged in 2022-11, with the labels that each got.

#1079 fix: Validate url domain for aws metadata urls
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockExternalAccountCredentialsTransport.java
Labels: size: m

#1078 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: size: l

#1092 feat: add smbios check for GCE residency detection
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
Labels: size: m

#1089 fix: empty string check for aws url validation
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
Labels: size: m

#1077 feat: next release from main branch is 1.13.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, size: s

#1100 fix: AwsCredentials should not call metadata server if security creds and region are retrievable through environment vars
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
Labels: size: l

#1082 feat: Introduce Environment Variable for Quota Project Id
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
  oauth2_http/clirr-ignored-differences.xml
  oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/functional/FTQuotaProjectId.java
Labels: size: l
