Repository googleapis/google-auth-library-java, pull requests merged in 2022-09, with the labels that each got.

#988 Fix: setting the retry count to default value and enabling ioexceptions to retry
  oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: m

#982 feat: adds configurable token lifetime support
  README.md
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ITWorkloadIdentityFederationTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthCredentialsTest.java
Labels: size: l

#990 docs(samples): modified comments in the samples and minor refactor
  samples/snippets/src/main/java/AuthenticateImplicitWithAdc.java
  samples/snippets/src/main/java/IdTokenFromImpersonatedCredentials.java
  samples/snippets/src/main/java/IdTokenFromMetadataServer.java
  samples/snippets/src/main/java/IdTokenFromServiceAccount.java
  samples/snippets/src/main/java/VerifyGoogleIdToken.java
  samples/snippets/src/test/java/SnippetsIT.java
Labels: samples, size: m
