Repository googleapis/google-auth-library-java, pull requests merged in 2022-12, with the labels that each got.

#993 Fix: Not loosing the access token when calling UserCredentials#ToBuil…
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: s

#1105 feat: Adding functional tests for Compute Engine
  oauth2_http/javatests/com/google/auth/oauth2/functional/FTComputeEngineCredentialsTest.java
Labels: size: m

#1087 feat: Add GDCH support
  oauth2_http/java/com/google/auth/oauth2/GdchCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GdchCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/JwtCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
  oauth2_http/testresources/cert.pem
Labels: size: xl

#1111 fix: Enforce Locale.US for AwsRequestSignerTest
  oauth2_http/javatests/com/google/auth/oauth2/AwsRequestSignerTest.java
Labels: size: xs
