Repository googleapis/google-auth-library-java, pull requests merged in 2022-10, with the labels that each got.

#1042 feat: Adding validation for psc endpoints
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: size: s

#945 fix: fixed javadoc errors
  oauth2_http/java/com/google/auth/oauth2/CredentialAccessBoundary.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/PluggableAuthCredentials.java
Labels: size: m

#1031 fix: Resolve race condition reported in #692
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsTest.java
Labels: size: m

#1074 chore: exclude requirements.txt file from renovate bot
  renovate.json
Labels: size: xs
