Repository googleapis/google-auth-library-java, pull requests merged in 2023-01, with the labels that each got.

#1125 fix: accessToken scopes clean serialization and default as empty list
  oauth2_http/java/com/google/auth/oauth2/AccessToken.java
  oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
  oauth2_http/javatests/com/google/auth/oauth2/AccessTokenTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Labels: size: m

#1131 fix: ensure both refreshMargin and expirationMargin are set when using OAuth2CredentialsWithRefresh
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2CredentialsWithRefresh.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2CredentialsWithRefreshTest.java
Labels: size: m

#1129 feat: adds external account authorized user credentials
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuthException.java
  oauth2_http/java/com/google/auth/oauth2/StsRequestHandler.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuthExceptionTest.java
Labels: size: xl

#1109 oauth2_http: Use Futures.getDone() instead of Future.get() in listener
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
Labels: size: xs

#1138 chore: adding push access for aion sdk team
  .github/sync-repo-settings.yaml
Labels: size: xs

#1136 docs: clarified Maven artifact for HTTP-based clients
  README.md
Labels: size: s

#1141 chore: add joined ownership with aion-sdk on 3pi and related files
  .github/CODEOWNERS
  owlbot.py
Labels: size: m
