Repository googleapis/google-auth-library-java, pull requests merged in 2023-02, with the labels that each got.

#1143 ci: add native profile for graalvm testing
  .kokoro/presubmit/graalvm-native-17.cfg
  .kokoro/presubmit/graalvm-native.cfg
  oauth2_http/pom.xml
  oauth2_http/resources/META-INF/native-image/com.google.auth/google-auth-library-oauth2-http/reflect-config.json
  oauth2_http/resources/META-INF/native-image/native-image.properties
  owlbot.py
  pom.xml
Labels: size: l

#1146 feat: Add PKCE to 3LO exchange.
  oauth2_http/java/com/google/auth/oauth2/DefaultPKCEProvider.java
  oauth2_http/java/com/google/auth/oauth2/PKCEProvider.java
  oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultPKCEProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Labels: size: l

#1150 fix: Removed url pattern validation for google urls in external account credential configurations
  README.md
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: size: m

#1148 fix: Java doc for DefaultPKCEProvider.java
  oauth2_http/java/com/google/auth/oauth2/DefaultPKCEProvider.java
  oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Labels: size: m

#1154 fix: create and reuse self signed jwt creds for better performance
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: size: s

#1113 fix: Make supporting classes of AwsCredentials serializable
  oauth2_http/java/com/google/auth/oauth2/AwsCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/SystemEnvironmentProvider.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthCredentialsTest.java
Labels: size: m

#1161 churn: backfilling a branch for LTS 3.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1162 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
  oauth2_http/javatests/com/google/auth/oauth2/TokenVerifierTest.java
Labels: automerge, size: l

#1164 fix: create and reuse self signed jwt creds for better performance
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: kokoro:force-run, automerge, size: s

#1166 fix: create and reuse self signed jwt creds for better performance (#…
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: size: s
