Repository googleapis/google-auth-library-java, pull requests merged in 2023-12, with the labels that each got.

#1329 chore: add java-shared-config as parent for consolidated version management
  .kokoro/build.sh
  oauth2_http/pom.xml
  owlbot.py
  pom.xml
Labels: size: m

#1344 chore: make kokoro cfgs version agnostic
  .kokoro/build.sh
  .kokoro/presubmit/graalvm-native-a.cfg
  .kokoro/presubmit/graalvm-native-b.cfg
  renovate.json
Labels: size: s

#1282 feat: multi universe support, adding universe_domain field
  credentials/java/com/google/auth/Credentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: xl

#1345 docs: Update README.md to link to Cloud authentication documentation rather than AIPs
  README.md
Labels: size: xs
