Repository googleapis/google-auth-library-java, pull requests merged in 2023-05, with the labels that each got.

#1201 chore: fix codeowners for aion-sdk
  .github/CODEOWNERS
Labels: size: m

#1188 feat: expose method to manually obtain ADC from gcloud CLI well-known…
  oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
  oauth2_http/java/com/google/auth/oauth2/GoogleAuthUtils.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleAuthUtilsTest.java
Labels: size: m

#1200 feat: updating readme for external account authorized user credentials
  README.md
Labels: automerge, size: s

#1172 fix: improve errors and warnings related to ADC
  oauth2_http/java/com/google/auth/oauth2/DefaultCredentialsProvider.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
Labels: size: m

#1204 chore: update Kokoro job to GraalVM 22.3.2
  .kokoro/presubmit/graalvm-native-17.cfg
  .kokoro/presubmit/graalvm-native.cfg
Labels: size: xs

#1206 fix: do not expose universe_domain yet
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
Labels: size: xs

#1205 fix: marking 503 as retryable for Compute credentials
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: m

#1211 deps: update doclet version to v1.9.0
  pom.xml
Labels: size: xs
