Repository googleapis/google-auth-library-java, pull requests merged in 2024-02, with the labels that each got.

#1364 fix: add missing copyright header
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountSupplierContext.java
Labels: size: s

#1362 docs: adds docs for supplier based external account credentials
  README.md
Labels: size: m

#1365 Revert "Revert "fix: Issue #1347: ExternalAccountCredentials serialization is broken""
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: size: s

#1371 docs: add supplier sections to table of contents
  README.md
Labels: size: xs

#1368 chore: enabling ut coverege check
  .github/workflows/sonar.yaml
  oauth2_http/pom.xml
Labels: size: m
