Repository googleapis/google-auth-library-java, pull requests merged in 2024-10, with the labels that each got.

#1503 feat: add metric headers
  credentials/java/com/google/auth/CredentialTypeForMetrics.java
  credentials/java/com/google/auth/Credentials.java
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IamUtils.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/MetricsUtils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MetricsUtilsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/TestUtils.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: l

#1526 fix: make some enum fields final
  credentials/java/com/google/auth/CredentialTypeForMetrics.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenProvider.java
  oauth2_http/java/com/google/auth/oauth2/MetricsUtils.java
Labels: size: xs

#1532 fix: switch to universe-domain endpoint for ComputeEngineCredentials
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
Labels: size: xs

#1528 feat: service sccount to service account impersonation to support universe domain
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
Labels: size: l

#1551 ci: Delete the auto-release workflow
  .github/workflows/auto-release.yaml
Labels: size: m

#1400 feat: Support querying S2A Addresses from MDS
  oauth2_http/java/com/google/auth/oauth2/S2A.java
  oauth2_http/java/com/google/auth/oauth2/S2AConfig.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/S2AConfigTest.java
  oauth2_http/javatests/com/google/auth/oauth2/S2ATest.java
Labels: size: l
