Repository googleapis/google-auth-library-java, pull requests merged in 2024-08, with the labels that each got.

#1452 fix: Retry sign blob call with exponential backoff
  oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
  oauth2_http/java/com/google/auth/oauth2/IamUtils.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/TokenVerifier.java
  oauth2_http/javatests/com/google/auth/oauth2/IamUtilsTest.java
Labels: size: m

#1484 chore: disable major version updates in renovate config
  renovate.json
Labels: size: xs

#1428 fix: ComputeEngineCredentials.createScoped should invalidate existing AccessToken
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Labels: size: m

#1457 chore: setup 1.23.x lts branch.
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1470 chore: use assertEquals to improve test error message
  oauth2_http/javatests/com/google/auth/oauth2/ExecutableResponseTest.java
  oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthHandlerTest.java
Labels: size: s

#1490 chore: remove owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  codecov.yaml
  owlbot.py
  synth.metadata
Labels: size: m
