Repository googleapis/google-auth-library-java, pull requests merged in 2024-01, with the labels that each got.

#1346 feat: adds universe domain support for compute credentials
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: size: l

#1334 fix: handle error-prone warnings
  appengine/java/com/google/auth/appengine/AppEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GdchCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdTokenCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2CredentialsWithRefresh.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
  oauth2_http/pom.xml
Labels: size: m

#1352 feat: Modify the refresh window to match go/async-token-refresh. Serverless tokens are cached until 4 minutes before expiration, so 4 minutes is the ideal refresh window.
  oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java
Labels: size: xs

#1284 fix: refactor compute and cloudshell credentials to pass quota project to base class
  oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/CloudShellCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/DefaultCredentialsProviderTest.java
Labels: size: m

#1244 chore: setup 1.19.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1358 fix: Issue #1347: ExternalAccountCredentials serialization is broken
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: do not merge, size: s

#1355 feat: adds universe domain for DownscopedCredentials and ExternalAccountAuthorizedUserCredentials
  oauth2_http/java/com/google/auth/oauth2/DownscopedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/AwsCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/DownscopedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/GoogleCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/PluggableAuthCredentialsTest.java
Labels: size: l

#1245 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: size: l

#1359 Revert "fix: Issue #1347: ExternalAccountCredentials serialization is broken"
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: size: s
