Repository googleapis/google-auth-library-java, pull requests merged in 2024-09, with the labels that each got.

#1469 chore: Add Cloud Java as Owners of Java Auth Library
  .github/CODEOWNERS
Labels: size: m

#1489 fix: Invalidate the SA's AccessToken when createScoped() is called
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
Labels: size: s

#1486 feat: updates UserAuthorizer to support retrieving token response directly with different client auth types
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
  oauth2_http/javatests/com/google/auth/TestUtils.java
  oauth2_http/javatests/com/google/auth/oauth2/MockTokenServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/OAuth2UtilsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Labels: size: xl

#1483 feat: add api key credential as client library authorization type
  credentials/java/com/google/auth/ApiKeyCredentials.java
  credentials/javatests/com/google/auth/ApiKeyCredentialsTest.java
Labels: size: m

#1456 chore: Migrate deprecated Guava `Charsets` to JDK's `StandardCharsets`
  oauth2_http/java/com/google/auth/oauth2/CloudShellCredentials.java
Labels: size: xs
