Repository googleapis/google-auth-library-java, pull requests merged in 2024-12, with the labels that each got.

#1571 feat: Add the generated ClientSideAccessBoundaryProto class for the Client-Side CAB feature
  cab-token-generator/java/com/google/auth/credentialaccessboundary/protobuf/ClientSideAccessBoundaryProto.java
  cab-token-generator/pom.xml
  pom.xml
Labels: size: xl

#1589 fix: JSON parsing of S2A addresses.
  oauth2_http/java/com/google/auth/oauth2/SecureSessionAgent.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Labels: size: s

#1570 chore: fix string format in mock
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Labels: automerge, size: xs

#1595 chore: Remove outdated TODO comment in GoogleAuthException
  oauth2_http/java/com/google/auth/oauth2/GoogleAuthException.java
Labels: size: xs
