Repository googleapis/google-auth-library-java, pull requests merged in 2025-02, with the labels that each got.

#1636 fix: Handle 404 and non 200 Status Code from MDS Identity Token calls
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/SecureSessionAgentTest.java
Labels: size: m

#1644 docs: Re-organize the README + Add a section on migrating to GoogleCredentials
  README.md
Labels: size: m

#1630 fix: respect token_uri from json in UserCredentials creation.
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: s

#1648 chore: update release-please username and add missing bots
  .github/workflows/members.json
Labels: size: xs

#1649 chore: add yoshi-automation account to members.json
  .github/workflows/members.json
Labels: size: xs

#1658 chore: add devoncarew to members.json
  .github/workflows/members.json
Labels: size: xs

#1661 chore: Disable automatic Protobuf updates from Renovate Bot
  renovate.json
Labels: size: xs

#1660 chore: use fully qualified org-members-path for multi-approvers
  .github/workflows/multi_approvers.yaml
Labels: size: xs

#1607 docs: Update README with client-side CAB instructions
  README.md
Labels: size: m

#1665 fix: remove unnecessary nexus-staging-maven-plugin activation
  appengine/pom.xml
  bom/pom.xml
  credentials/pom.xml
  oauth2_http/pom.xml
  pom.xml
Labels: size: m

#1662 fix: Add cab-token-generator module to Auth BOM
  bom/pom.xml
Labels: size: xs

#1656 chore: Add test for non-2xx responses from idTokenWithAudience calls
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
Labels: size: m

#1586 feat: add client logging with slf4j
  .github/workflows/ci.yaml
  .github/workflows/sonar.yaml
  .kokoro/build.sh
  .kokoro/dependencies.sh
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IamUtils.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/LoggerProvider.java
  oauth2_http/java/com/google/auth/oauth2/LoggingUtils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/Slf4jLoggingHelpers.java
  oauth2_http/java/com/google/auth/oauth2/Slf4jUtils.java
  oauth2_http/java/com/google/auth/oauth2/UserCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/LoggingTest.java
  oauth2_http/javatests/com/google/auth/oauth2/LoggingUtilsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/Slf4jUtilsLogbackTest.java
  oauth2_http/javatests/com/google/auth/oauth2/Slf4jUtilsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/TestAppender.java
  oauth2_http/javatests/com/google/auth/oauth2/UserCredentialsTest.java
  oauth2_http/pom.xml
  pom.xml
Labels: size: xl

#1698 feat: next release from main branch is 1.34.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1701 Revert "feat: next release from main branch is 1.34.0 (#1698)"
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1702 feat: next release from main branch is 1.34.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s
