Repository googleapis/google-auth-library-java, pull requests merged in 2025-01, with the labels that each got.

#1583 feat: Implement refreshCredentialsIfRequired for intermediate token r…
  cab-token-generator/java/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactory.java
  cab-token-generator/javatests/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactoryTest.java
  cab-token-generator/pom.xml
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
  pom.xml
Labels: size: xl

#1606 ci: Disable Sonar if PR comes from a fork
  .github/workflows/sonar.yaml
Labels: size: xs

#1558 feat: Support transport and binding-enforcement MDS parameters.
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
Labels: size: m

#1616 chore(ci): set up release-please
  .release-please-manifest.json
  release-please-config.json
Labels: size: s

#1612 chore: add multi-approvers check
  .github/workflows/members.json
  .github/workflows/multi_approvers.yaml
Labels: size: s

#1598 feat: Implement Client-Side CAB token generation.
  cab-token-generator/java/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactory.java
  cab-token-generator/javatests/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactoryTest.java
  cab-token-generator/pom.xml
  oauth2_http/javatests/com/google/auth/oauth2/MockStsTransport.java
  pom.xml
Labels: size: l

#1620 docs: promote use of bill of materials in quickstart documentation
  README.md
Labels: automerge, size: m

#1566 feat: ImpersonatedCredentials to support universe domain for idtoken and signblob
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IamUtils.java
  oauth2_http/java/com/google/auth/oauth2/ImpersonatedCredentials.java
  oauth2_http/java/com/google/auth/oauth2/OAuth2Utils.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IamUtilsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/ImpersonatedCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockIAMCredentialsServiceTransport.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Labels: size: l

#1622 chore: add renovate-bot and release-please to members
  .github/workflows/members.json
Labels: size: xs

#1619 chore: Add warnings to users about using credentials from external sources
  README.md
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountAuthorizedUserCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/java/com/google/auth/oauth2/GoogleCredentials.java
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountCredentials.java
Labels: size: m

#1632 chore: Add Spanner team to members.json for 2P check
  .github/workflows/members.json
Labels: size: xs

#1633 chore: add step to download members.json
  .github/workflows/multi_approvers.yaml
Labels: size: s

#1642 chore: add Go team to members for 2P reviews
  .github/workflows/members.json
Labels: size: xs

#1640 chore: add Ruby team to members for 2P reviews
  .github/workflows/members.json
Labels: size: xs

#1641 chore: add Python team to members for 2P reviews
  .github/workflows/members.json
Labels: size: xs

#1643 chore: add C++ team to members for 2P reviews
  .github/workflows/members.json
Labels: size: m

#1645 chore: add Rust team to members for 2P reviews
  .github/workflows/members.json
Labels: size: xs
