Repository googleapis/google-auth-library-java, pull requests merged in 2025-04, with the labels that each got.

#1722 feat: Implement X509 certificate provider
  oauth2_http/java/com/google/auth/mtls/CertificateSourceUnavailableException.java
  oauth2_http/java/com/google/auth/mtls/WorkloadCertificateConfiguration.java
  oauth2_http/java/com/google/auth/mtls/X509Provider.java
  oauth2_http/javatests/com/google/auth/mtls/WorkloadCertificateConfigurationTest.java
  oauth2_http/javatests/com/google/auth/mtls/X509ProviderTest.java
Labels: size: l

#1735 chore: add suzmue to members.json
  .github/workflows/members.json
Labels: size: xs

#1728 fix: Do not add padding in Client-Side CAB tokens.
  cab-token-generator/java/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactory.java
  cab-token-generator/javatests/com/google/auth/credentialaccessboundary/ClientSideCredentialAccessBoundaryFactoryTest.java
Labels: size: s

#1723 chore: add link to guide on enable debug logging
  README.md
Labels: size: xs

#1737 chore: pin version of multi-approvers workflow
  .github/workflows/multi_approvers.yaml
Labels: size: xs

#1742 chore: add viacheslav rostovtsev to members.json
  .github/workflows/members.json
Labels: size: xs
