Repository googleapis/google-auth-library-java, pull requests merged in 2025-10, with the labels that each got.

#1806 ci: upgrade tests to JDK 25
  .github/workflows/ci.yaml
Labels: size: xs

#1810 docs: Migrate documentation from README to the offical doc site
  README.md
Labels: size: xl

#1812 chore: Restore the testing requirements in README
  README.md
Labels: size: s
