Repository googleapis/google-auth-library-java, pull requests merged in 2025-05, with the labels that each got.

#1706 fix: Handle optional fields with null JSON value in ExternalAccountCredentials gracefully
  oauth2_http/java/com/google/auth/oauth2/ExternalAccountCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ExternalAccountCredentialsTest.java
Labels: size: s

#1736 feat: Add support for mTLS authentication via X.509 certificates
  oauth2_http/java/com/google/auth/mtls/MtlsHttpTransportFactory.java
  oauth2_http/java/com/google/auth/mtls/X509Provider.java
  oauth2_http/java/com/google/auth/oauth2/CertificateIdentityPoolSubjectTokenSupplier.java
  oauth2_http/java/com/google/auth/oauth2/FileIdentityPoolSubjectTokenSupplier.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentialSource.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolCredentials.java
  oauth2_http/java/com/google/auth/oauth2/IdentityPoolSubjectTokenSupplier.java
  oauth2_http/java/com/google/auth/oauth2/UrlIdentityPoolSubjectTokenSupplier.java
  oauth2_http/javatests/com/google/auth/oauth2/CertificateIdentityPoolSubjectTokenSupplierTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsSourceTest.java
  oauth2_http/javatests/com/google/auth/oauth2/IdentityPoolCredentialsTest.java
  oauth2_http/testresources/x509_leaf_certificate.pem
Labels: size: xl

#1746 feat: Return X509 certificate chain as the subject token.
  oauth2_http/java/com/google/auth/oauth2/CertificateIdentityPoolSubjectTokenSupplier.java
  oauth2_http/javatests/com/google/auth/oauth2/CertificateIdentityPoolSubjectTokenSupplierTest.java
  oauth2_http/testresources/trust_chain_with_leaf.pem
  oauth2_http/testresources/trust_chain_without_leaf.pem
  oauth2_http/testresources/trust_chain_wrong_order.pem
  oauth2_http/testresources/x509_intermediate_certificate.pem
Labels: size: l

#1751 chore: add jdk 24 to test matrixes
  .github/workflows/ci.yaml
Labels: size: xs

#1450 fix: IdTokenCredentials should fetch license id claim when requested
  oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ComputeEngineCredentialsTest.java
  oauth2_http/javatests/com/google/auth/oauth2/MockMetadataServerTransport.java
Labels: size: s

#1752 fix: update approval_prompt=force to prompt=consent
  oauth2_http/java/com/google/auth/oauth2/UserAuthorizer.java
  oauth2_http/javatests/com/google/auth/oauth2/UserAuthorizerTest.java
Labels: size: xs

#1754 feat: support ability to set universe domain in ServiceAccountJwtAccessCredentials
  oauth2_http/java/com/google/auth/oauth2/ServiceAccountJwtAccessCredentials.java
  oauth2_http/javatests/com/google/auth/oauth2/ServiceAccountJwtAccessCredentialsTest.java
Labels: size: m
